NDcPP_v2_2e.adoc
=> Rfi-202102 Changes

NDcPP_v2_2e.adoc
=> Update 070721 1

NDcPP_v2_2e.adoc
Additional updates based on TLSWG NDcPP Word document.
=> Update 07072021 2

NDcPP_v2_2e.adoc
FMT_SMF.1.1 - edited
FIA_X509_EXT.1.1/ITT - edited
FCS_TLSS_EXT.2.1 - edited
FCS_TLSS_EXT.2.4 - added
A.7.1.2 edited section #
B.3.1.1 added wording
B.3.1.6 added and edited wording
C. Extended Component Definitions
FCS_TLSS_EXT.2.1 - edited, no app notes included in C. ECD
FCS_TLSS_EXT.2.4 - added, no app notes included in C. ECD
=> NDcPP update w/ TLSv1.3 proposal

NDcPP_v2_2e.adoc
Correcting Application Note numbering and large text with quotes throughout document.
=> Updated maintenance branch

NDcPP_v2_2e.adoc
Initial update to FCS_DTLSS_EXT.1 and appendix C material.
Also made one minor update to FCS_TLSS_EXT.1.5 to sync with FCS_DTLSS_EXT.1.8 to accommodate (what I think is) a better grammar update.
=> Applied ADOC formatting and content updates to FCS_DTLSS_EXT.1 and in Appendix C.

ND Supporting Document 2_2.adoc
Updates to FCS_TLSC_EXT.1.7. Please review.
=> Tlswg ak fcs tlsc ext.1.7 update

ND Supporting Document 2_2.adoc
=> Removal of Test 1 and addition of Tests 1 - 4 for FCS_TLSC_EXT.1.4

ND Supporting Document 2_2.adoc
=> Tlswg ak fcs tlsc ext.1.6 update

ND Supporting Document 2_2.adoc, NDcPP_v2_2e.adoc
Formatting cleanup for TLSv1.3 updates (cPP and SD)
=> TLS-tlsv1.3_cleanup-kk-01042022

ND Supporting Document 2_2.adoc, NDcPP_v2_2e.adoc
Updated to include FAU_STG_EXT.1/LocSpace SFRs, AAs, and other changes.
=> fau_local 2022feb07 km

NDcPP_v2_2e.adoc
Issue #62, NIAP Comment on FCS_RBG_EXT.1
=> Issue #62, NIAP Comment on FCS_RBG_EXT.1

NDcPP_v2_2e.adoc
Addressed comments from NIAP after they ran their comparison script.
=> NIAP Formatting Changes

NDcPP_allowed_with_list.adoc, NDcPP_v2_2e.adoc
Added allowed with list in adoc format.
Added URL to NDcPP (the link won't work until this commit is merged to main).
=> Added allowed-with list 2

ND Supporting Document 2_2.adoc, NDcPP_v2_2e.adoc
Integration of NIT TDs:
TD0527, TD0528, TD0536, TD0537, TD0538,TD0547,TD0563, TD0564, TD0580, TD0581, TD0591, TD0592, TD0631, TD0632 ,TD0633, TD0638
=> Remaining NIT TD Integration for NDcPPv3.0

ND Supporting Document 2_2.adoc
Made changes to SD to add TD0670, https://www.niap-ccevs.org/Documents_and_Guidance/view_td.cfm?TD=0670.
=> Add-TD0670-kk

NDcPP_v2_2e.adoc
To address Issue #84 , in lines 4679 and 4717 added [appendix].
To address Issue #85 , corrected line 3440 with proper syntax _+++<u>+++. All other lines were corrected during other updates.
=> Fixed Appendix D and E

ND Supporting Document 2_2.adoc
Fix SD paragraph #s and table-links
=> Fix-SD-paragraph#s-table-links

NDcPP_v3_0.adoc
Resolution of a number of editorial issues (formatting, typo's etc.) for v3.0. Includes fixes for:
- 154
- 159
- 153
- 152
- 140
- 139
- 138
- 137
- 136
- 102
=> Various v3 editorial issues. 

ND_Supporting_Document_3_0.adoc
Removed the negative tests and remarks associated with the negative tests.
=> (D)TLS signature algorithm tests

ND_Supporting_Document_3_0.adoc, NDcPP_v3_0.adoc
Fixes for the following issues:
https://github.com/ND-iTC/Documents/issues/134
https://github.com/ND-iTC/Documents/issues/170
https://github.com/ND-iTC/Documents/issues/171
https://github.com/ND-iTC/Documents/issues/179
https://github.com/ND-iTC/Documents/issues/192
https://github.com/ND-iTC/Documents/issues/193
https://github.com/ND-iTC/Documents/issues/198
=> TLSWG v3 editorial fixes

NDcPP_allowed_with_list.adoc
Updated allowed with list for v3.0
=> Updated allowed with list

ND_Supporting_Document_3_0.adoc, NDcPP_v3_0.adoc
https://github.com/ND-iTC/Documents/issues/116
https://github.com/ND-iTC/Documents/issues/200
https://github.com/ND-iTC/Documents/issues/196
https://github.com/ND-iTC/Documents/issues/195
https://github.com/ND-iTC/Documents/issues/178
=> TLSWG v3 edits 2nd round

ND_Supporting_Document_3_0.adoc
=> Small fix for #118

NDcPP_v3_0.adoc
I have made the changes relating to issues #107, #115, #123, and #229. Please note, #229 and #123 are related, so the changes are the same as per our discussion.
=> Updates relating to #107, #115, #123, and #229.

ND_Supporting_Document_3_0.adoc, NDcPP_v3_0.adoc
Completed #105 (minor edit), #106 (added app note), #117 (removed a test), #135 (corrected SFR names), and #155 (same as 135).
=> Completed #105, #106, #117, #135, and #155.

NDcPP_allowed_with_list.adoc
Allowed with list updated to include NDcPPv3.0
=> Allowed with list updated

ND_Supporting_Document_3_0.adoc, NDcPP_v3_0.adoc
Plus some additional tidying up of cross-references and version numbering.
=> CCMB Edits to remove references to 'user'

NDcPP_v3_0.adoc
Updated date and version in Introduction section
=> Updated date and version in Introduction section

NDcPP_v3_0.adoc
Removed word repetition, added full stop, and corrected spelling.
=> Typo fixes

ND_Supporting_Document_3_0.adoc, NDcPP_v3_0.adoc
cPP comments 16, 19, 20, 28, 36, 39
SD comment 44, 45, 46, 47, 48, 49, 50, 51
=> TLS editorial fixes base on NIAP comments

ND_Supporting_Document_3_0.adoc, NDcPP_v3_0.adoc
Codified application note details into FPT_TST_EXT.1.1
Added FPT_TST_EXT.1.2
Added failure state description to FPT_TST_EXT.1
=> Updates to FPT_TST_EXT.1

ND_Supporting_Document_3_0.adoc, NDcPP_allowed_with_list.adoc, NDcPP_v3_0.adoc
=> 3.0e-ver-date-change

ND_Supporting_Document_3_0.adoc, NDcPP_v3_0.adoc
RFI202308
https://ccusersforum.onlyoffice.co/Products/Files/DocEditor.aspx?fileid=8581666&action=view
Issue #327
https://github.com/ND-iTC/Documents/issues/327
Issue #316
https://github.com/ND-iTC/Documents/issues/316
Issue #317
https://github.com/ND-iTC/Documents/issues/317
Issue #318
https://github.com/ND-iTC/Documents/issues/318
=> (D)TLS RFI and issues

ND_Supporting_Document_3_0e.adoc, NDcPP_v3_0e.adoc
PR to address Issue #368 NTPv4 authentication with AES-CMAC (RFC 8573)
=> Issue #368
